services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
#    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=Ikiseh@1
      - MYSQL_DATABASE=iFarmer
    ports:
      - "3307:3306"  # Host port 3307 to container port 3306
    volumes:
      - db:/var/lib/mysql



  app:
    image: maven:3.8.5-openjdk-17
    depends_on:
      - mysqldb
    build: .
#    restart: on-failure
#    env_file: ./.env
    ports:
      - "6868:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
         "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/iFarmer",
         "spring.datasource.username" : "root",
         "spring.datasource.password" : "Ikiseh@1",
         "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
         "spring.jpa.hibernate.ddl-auto" : "update"
       }'

    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
