services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=iFarmer
    ports:
      - "3307:3306"  # Host port 3307 to container port 3306
    volumes:
      - db:/var/lib/mysql

  app:
    image: maven:3.8.5-openjdk-17
    depends_on:
      - mysqldb
    build: .
    ports:
      - "6868:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
         "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/iFarmer",
         "spring.datasource.username" : ${DB_USER},
         "spring.datasource.password" : ${DB_PASSWORD},
         "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
         "spring.jpa.hibernate.ddl-auto" : "update"
       }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
